name: Deploy Discord Bot to Azure

on:
  push:
    branches:
      - main

jobs:
  build-and-deploy:
    runs-on: ubuntu-latest

    steps:
      - name: âœ… Checkout code
        uses: actions/checkout@v3

      - name: ğŸ” Change directory to bot folder
        run: cd VUKbot
        shell: bash

      - name: ğŸ Set up Python
        uses: actions/setup-python@v4
        with:
          python-version: '3.11'

      - name: ğŸ“¦ Install dependencies
        working-directory: ./VUKbot
        run: pip install -r requirements.txt

      - name: ğŸ› ï¸ Compile Python files
        working-directory: ./VUKbot
        run: python -m compileall .

      - name: ğŸš€ Deploy to Azure Web App
        uses: azure/webapps-deploy@v2
        with:
          app-name: VUKBot
          publish-profile: ${{ secrets.AZURE_WEBAPP_PUBLISH_PROFILE }}
          package: ./VUKbot
